main:
  device: cuda
  dataset: hm3dsem
  # scene_id: 00843-DYehNKdT76V # scene0011_00
  scene_id: 00829-QaLdnwvtxbs
  floor_id: 0
  split: val
  package_path: /home/cassie/Workspace/HOV-SG/hovsg/
  dataset_path: /home/cassie/Workspace/HOV-SG/hovsg/data/hm3dsem_walks/
  raw_data_path: /home/cassie/Workspace/HOV-SG/hovsg/data/versioned_data/hm3d-0.2/hm3d
  save_path: /home/cassie/Workspace/HOV-SG/hovsg/data/scene_graphs
dataset:
  hm3dsem:
    gt_skip_frames: 1
models:
  clip:
    type:  ViT-H-14 # ViT-L/14@336px # ViT-H-14
    checkpoint: /home/cassie/Workspace/HOV-SG/checkpoints/laion2b_s32b_b79k.bin 
    # checkpoint: checkpoints/ovseg_clipl14_9a1909.pth checkpoints/laion2b_s32b_b79k.bin
  sam:
    checkpoint: /home/cassie/Workspace/HOV-SG/checkpoints/sam_vit_h_4b8939.pth
    type: vit_h
    points_per_side: 12
    pred_iou_thresh: 0.88
    points_per_batch: 144
    crop_n_layers: 0
    stability_score_thresh: 0.95
    min_mask_region_area: 100
eval:
  association_metric: overlap
  obj_labels: NYU_V2_LABELS
  hm3dsem:
    top_k_object_semantic_eval: [1, 5, 10, 20, 50]
    # top_k_object_semantic_eval: [5, 10, 25, 100, 250, 500]
    obj_labels: NYU_V2_LABELS